services:
  db:
    image: postgres:16-alpine
    container_name: go_task_manager_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
